// Code generated by MockGen. DO NOT EDIT.
// Source: hash (interfaces: Hash32)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockHash32 is a mock of Hash32 interface
type MockHash32 struct {
	ctrl     *gomock.Controller
	recorder *MockHash32MockRecorder
}

// MockHash32MockRecorder is the mock recorder for MockHash32
type MockHash32MockRecorder struct {
	mock *MockHash32
}

// NewMockHash32 creates a new mock instance
func NewMockHash32(ctrl *gomock.Controller) *MockHash32 {
	mock := &MockHash32{ctrl: ctrl}
	mock.recorder = &MockHash32MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockHash32) EXPECT() *MockHash32MockRecorder {
	return m.recorder
}

// BlockSize mocks base method
func (m *MockHash32) BlockSize() int {
	ret := m.ctrl.Call(m, "BlockSize")
	ret0, _ := ret[0].(int)
	return ret0
}

// BlockSize indicates an expected call of BlockSize
func (mr *MockHash32MockRecorder) BlockSize() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockSize", reflect.TypeOf((*MockHash32)(nil).BlockSize))
}

// Reset mocks base method
func (m *MockHash32) Reset() {
	m.ctrl.Call(m, "Reset")
}

// Reset indicates an expected call of Reset
func (mr *MockHash32MockRecorder) Reset() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockHash32)(nil).Reset))
}

// Size mocks base method
func (m *MockHash32) Size() int {
	ret := m.ctrl.Call(m, "Size")
	ret0, _ := ret[0].(int)
	return ret0
}

// Size indicates an expected call of Size
func (mr *MockHash32MockRecorder) Size() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Size", reflect.TypeOf((*MockHash32)(nil).Size))
}

// Sum mocks base method
func (m *MockHash32) Sum(arg0 []byte) []byte {
	ret := m.ctrl.Call(m, "Sum", arg0)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Sum indicates an expected call of Sum
func (mr *MockHash32MockRecorder) Sum(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sum", reflect.TypeOf((*MockHash32)(nil).Sum), arg0)
}

// Sum32 mocks base method
func (m *MockHash32) Sum32() uint32 {
	ret := m.ctrl.Call(m, "Sum32")
	ret0, _ := ret[0].(uint32)
	return ret0
}

// Sum32 indicates an expected call of Sum32
func (mr *MockHash32MockRecorder) Sum32() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sum32", reflect.TypeOf((*MockHash32)(nil).Sum32))
}

// Write mocks base method
func (m *MockHash32) Write(arg0 []byte) (int, error) {
	ret := m.ctrl.Call(m, "Write", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write
func (mr *MockHash32MockRecorder) Write(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockHash32)(nil).Write), arg0)
}
